# 1.Create a numpy array containing the numbers from 1 to 10, and then reshape it to a 2x5 matrix.

In [4]:
import numpy as np
import pandas as pd

method 1

In [5]:
array=np.arange(1,11).reshape(2,5)
print(array)


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [ ]:
method 2

In [19]:
array=np.linspace(1,10,10,dtype=int).reshape(2,5)
print(array)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


method 3

In [20]:
array=np.array(range(1,11)).reshape(2,5)
print(array)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [ ]:
method 4

In [23]:
array=np.random.choice(range(1,11),size=(2,5),replace=False)
print(array)

[[ 4  8  3 10  2]
 [ 5  7  9  1  6]]


 # 2.Create a numpy array containing the numbers from 1 to 20, and then extract the elements between the 5th and 15th index.

In [24]:
array=np.arange(1,21)
print(array)
print("Extracted elemnts are:",array[5:15])

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
Extracted elemnts are: [ 6  7  8  9 10 11 12 13 14 15]


# 3.Create a Pandas series with the following data: {'apples': 3, 'bananas': 2, 'oranges': 1}. Then, add a new item to the series with the key 'pears' and the value 4

In [38]:
fruits=pd.Series({'apples':3, 'bananas':2, 'oranges':1})
print(fruits)
fruits['pears']=4
print("New fruits list is:\n",fruits)

apples     3
bananas    2
oranges    1
dtype: int64
New fruits list is:
 apples     3
bananas    2
oranges    1
pears      4
dtype: int64


 # 4.Create a dataframe with the following columns: name, age, and gender. The dataframe should have 10 rows of data

In [2]:
import random

In [6]:
Name=['Amelia','Riz','Rayan','Hima','Josh','Kevin','Finly','Rash','lima','Lee','Mia']
Gender=['male','female']

data={
      'Name':[random.choice(Name) for i in range(10)],
      'Gender':[random.choice(Gender) for i in range(10)],
      'Age':np.random.randint(18,60, size=10)
     }   
df=pd.DataFrame(data)
print(df)

     Name  Gender  Age
0   Kevin    male   52
1    lima  female   37
2    lima    male   51
3   Finly  female   49
4   Kevin    male   39
5   Kevin  female   26
6   Rayan    male   36
7    Josh  female   52
8   Rayan  female   41
9  Amelia  female   43


# 5.Add a new column to the data frame created in question 1, called occupation. The values for this column should be Programmer, Manager, and Analyst, corresponding to the rows in the datafra

In [54]:
Occupations=['Programmer','Manager','Analyst']
df['Occupations']=[random.choice(Occupations) for i in range(10)]    # or range in (df.shape[0])
print(df)

    Name  Gender  Age Occupations
0   Hima  female   58  Programmer
1    Mia  female   32  Programmer
2    Mia  female   45     Analyst
3    Lee  female   25  Programmer
4  Finly    male   49  Programmer
5   lima    male   21  Programmer
6    Riz    male   45  Programmer
7    Riz    male   18  Programmer
8    Lee    male   58  Programmer
9    Mia    male   48     Manager


# 6.Select the rows of the dataframe where the age is greater than or equal to 30

In [58]:
 print(" Data with Age  grater than or equal to 30 is :\n",df[df['Age']>=30])

 Data with Age  grater than or equal to 30 is :
     Name  Gender  Age Occupations
0   Hima  female   58  Programmer
1    Mia  female   32  Programmer
2    Mia  female   45     Analyst
4  Finly    male   49  Programmer
6    Riz    male   45  Programmer
8    Lee    male   58  Programmer
9    Mia    male   48     Manager


# 7. Convert this dataframe to a csv file and read that csv file, finally display the contents.

In [60]:
df.to_csv("Assignment_7.csv",index=False)
READ=pd.read_csv("Assignment_7.csv")
print("The file content is :\n",READ)

The file content is :
     Name  Gender  Age Occupations
0   Hima  female   58  Programmer
1    Mia  female   32  Programmer
2    Mia  female   45     Analyst
3    Lee  female   25  Programmer
4  Finly    male   49  Programmer
5   lima    male   21  Programmer
6    Riz    male   45  Programmer
7    Riz    male   18  Programmer
8    Lee    male   58  Programmer
9    Mia    male   48     Manager
